# Generate dfs for PCA/UMAP analysis of Perth09 data

In [1]:
import altair as alt

import pandas as pd

import itertools

import numpy

import warnings
warnings.filterwarnings('ignore')

from IPython.utils import io

import glob

In [2]:
import os
os.chdir('../../')

In [3]:
# define samples in each age cohort
sample_dict = {
    "vietnam_ped": [
        "age 2.1 (Vietnam)", 
        "age 2.2 (Vietnam)",
        "age 2.4 (Vietnam)",
        "age 2.5 (Vietnam)",
        "age 2.5b (Vietnam)",
        "age 3.3 (Vietnam)", 
        "age 3.3b (Vietnam)",
        "age 3.4 (Vietnam)", 
        "age 3.5 (Vietnam)",
    ], 
    "vietnam_adult": [
        "age 30.5 (Vietnam)",
        "age 31.5 (Vietnam)",
        "age 33.5 (Vietnam)",
    ],
    "misc_adult": [
        "age 21 (Seattle)",
        "age 53 (Seattle)",
        "age 64 (Seattle)",
        "age 65 (Seattle)",
    ],
    "ferret": [
        "ferret 1 (Pitt)",
        "ferret 2 (Pitt)",
        "ferret 3 (Pitt)",
        "ferret (WHO)",
    ]
}

merged_escape = pd.read_csv(f'results/perth2009/merged_escape.csv')[['name', 'site', 'wildtype', 'mutant', 'escape']]

def find_sample_type(sample_name):
    for sample_type, sample_list in sample_dict.items():
        if sample_name in sample_list:
            return sample_type
    return None

merged_escape['sample_type'] = merged_escape['name'].apply(find_sample_type)
merged_escape = merged_escape.rename(columns={'name': 'serum'})

# floor escape at 0
merged_escape_floor = merged_escape.copy()
merged_escape_floor['escape'] = merged_escape_floor['escape'].apply(lambda x: 0 if x < 0 else x)

merged_escape.head()

                serum site wildtype mutant  escape    sample_type
0  age 30.5 (Vietnam)  159        F      G   3.482  vietnam_adult
1  age 30.5 (Vietnam)  159        F      N   2.451  vietnam_adult
2  age 30.5 (Vietnam)  159        F      H   2.334  vietnam_adult
3  age 30.5 (Vietnam)  159        F      T   1.514  vietnam_adult
4  age 30.5 (Vietnam)  159        F      S   1.195  vietnam_adult

In [4]:
merged_escape.to_csv('scratch_notebooks/figure_drafts/230721_perth09_df.csv')
merged_escape_floor.to_csv('scratch_notebooks/figure_drafts/230721_perth09_df_floored.csv')